include: package:lint/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    prefer_single_quotes: true
    always_specify_types: true
    avoid_classes_with_only_static_members: false
    sort_pub_dependencies: false
    avoid_relative_lib_imports: true
    always_use_package_imports: true
