name: kzm
description: A new Flutter application.

publish_to: 'none'

version: 1.2.182
environment:
  sdk: ">=2.9.0-13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  responsive_builder: ^0.3.0
  flutter_cache_manager: ^3.3.1
  motion_toast: ^2.6.7
  m_toast: ^0.1.8
  socket_io_client: ^1.0.2
  provider: ^6.0.0
  get: ^4.6.3
  getflutter: ^1.1.3
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  font_awesome_flutter: ^8.11.0
  supercharged: ^2.1.1
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  build_resolvers: ^1.5.2
  flutter_html: ^2.1.2
  version: ^1.2.0
  device_info: ^2.0.0
  webview_flutter: ^2.0.13
  star_rating: ^0.11.0
  file_picker: ^4.6.1
  file: any
  flutter_local_notifications: ^9.4.1
  image_picker: ^0.8.0+3
  carousel_slider: ^4.2.1
  url_launcher: ^6.0.12
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  cached_network_image: 3.2.2
  modal_bottom_sheet: ^2.0.1
  advance_pdf_viewer: ^2.0.1
  video_player: ^2.1.1
  mask_text_input_formatter: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  shimmer: ^2.0.0
  flutter_screenutil: ^5.5.2
  connectivity_plus: ^2.0.2
  collection: ^1.15.0
  table_calendar: ^3.0.3
  syncfusion_flutter_calendar: ^20.1.56
  sticky_grouped_list: ^3.1.0
  flutter_launcher_icons: ^0.9.2
  search_page: ^2.0.0+1
  hive_listener: ^1.2.1
  package_info: ^2.0.2
  permission_handler: ^10.0.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_crashlytics: ^3.0.17
  local_auth: ^2.0.0
  new_version: ^0.3.1
  flutter_app_version_checker: ^0.3.2
  open_file_safe: ^3.2.3

flutter_intl:
  enabled: true

dependency_overrides:
  path: 1.7.0
  path_provider: ^2.0.1
  plugin_platform_interface: ^2.0.0
  http_parser: ^4.0.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner: ^1.11.0
  lint: ^1.7.2
  flutter_native_splash: ^1.2.3
  pretty_json: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/faceId.png
    - assets/images/svg/
    - assets/images/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  fill: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/kzm-icon.jpg"